feat1=false
feat2=true
feat3=false
feat4=com/janetfilter/core/Launcher.class;com/novitechie/PrivacyPlugin.class
feat5=reborn;梁 超;idea-set;violetfreesia;ckey.run;menorah parapet;IDE`a Scripts;iDeb;SchrodingersFish;gurgles tumbles
feat6=true